version: "3.8"

services:
  sdbus-ls:
    build:
      context: .
      dockerfile: Dockerfile
    image: sdbus-ls:latest
    container_name: sdbus-dev
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - .:/home/devuser/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
    working_dir: /home/devuser/src
